# কোয়ান্টাম মেকানিক্সের অদ্ভুত জগৎ {#quick-glance}

ঊনবিংশ শতকের শেষের দশকগুলোতে বদলে যেতে শুরু করল আমাদের চেনা-জানা পৃথিবী। পরিবর্তনটা  ঘটল বড়-ছোট দুই জগতেই। একদিকে ইথারের ধারণা বিলুপ্তি ও আলোর বেগের ধ্রুবতা ক্রমশ জন্ম দিল আপেক্ষিকতা তত্ত্বের। পৃথিবী ও মহাবিশ^ নতুন রূপে ধরা দিল মানুষের চোখে। সে এক বিস্ময় জাগানো রূপ। তবে তার চেয়ে বড় বিস্ময় হয়ে এল কোয়ান্টাম মেকানিক্স। আজব আজব ঘটনার জন্ম দিতে দুইটি তত্ত্ব যেন একে অপরের সাথে খেলায় মেতে ওঠল। নির্দিষ্ট সময় পরে দুই যমজের বয়স কম-বেশি হবে বলে আপেক্ষিতা যদি তাক লাগিয়ে দেয়, তবে আরও বেশি তাক লাগিয়ে দেবে একই কণার একই সাতে দুই আলাদা পথে চলার ঘটনা। কিংবা, বলা নেই, কওয়া নেই, হঠাৎ করে ভোজবাজির মতো শূন্য থেকে পয়দা হয়ে গেল আস্ত একটি কণা! এমন আরও নানান আজব ঘটনার জন্যে কোয়ান্টাম মেকানিক্স খুব বিখ্যাত। পদার্থবিদ রিচার্ড ফাইনম্যান তো বলেছিলেন, 

> আমার মনে হয়, আমি নিশ্চিন্তে বলতে পারি, কেউই কোয়ান্টাম মেকানিক্স বোঝেন না।


তত্ত্বের শুরু মোটামুটি ম্যাক্স প্ল্যাঙ্কের হাত ধরে। ঊনবিংশ শতকের মাঝামাঝি সময়ে কৃষ্ণবস্তুর বিকিরণ নিয়ে একটি সমস্যা ছিল বিজ্ঞান জগতে। সে সময় আলো বিদুৎ-চৌম্বকীয় তরঙ্গ হিসেবে পরিচিত ছিল। সব কিছু ব্যাখ্যা করা হত ম্যাক্সওয়েলের সমীকরণ দিয়ে। আলোকে নিছক তরঙ্গ ধরে নিয়ে। কিন্তু নতুন নতুন উপাত্তকে ব্যাখ্যা করতে ক্রমাগত ব্যর্থ হচ্ছিল ম্যাক্সওয়েলের সমীকরণগুলো। ১৯০০ সালের কথা। প্ল্যাঙ্ক তখন ম্যাক্সওয়েলের ছাত্র। পরীক্ষায় একটি প্রশ্নে কৃষ্ণবস্তুর বিকিরণ ব্যাখ্যা করতে বলা হলো। প্ল্যাঙ্ক এক দুঃসাহসী কাজ করে বসলেন। এতদিন যাকে তরঙ্গ বলে আসা হচ্ছে, তাকেই কিনা তিনি কণা হিসেবে ধরতে গেলেন!

বললেন, বিদুৎ-চৌম্বকীয় শক্তি নির্গত হয় বিচ্ছিন্ন গুচ্ছ আকারে। এই গুচ্ছেরই নাম কোয়ান্টা। তিনি বললেন, প্রতিটি কোয়ান্টার শক্তি নির্ভর করে শুধুমাত্র এর কম্পাঙ্কের ওপর। আগে মনে করা হত, কোনো বস্তু থেকে সব কম্পাঙ্কের তরঙ্গ সমান হারে নির্গত হয়। কিন্তু সেটা হলে বস্তু থেকে নির্গত শক্তির পরিমাণ হয় অসীম, যা অসম্ভব। এটাই ছিল বিখ্যাত কৃষ্ণবস্তু বিকিরণ সমস্যা। প্ল্যাঙ্ক বললেন, বড় কম্পাঙ্কের তরঙ্গ অপেক্ষাকৃত কম নির্গত হয়। কেন? কারণ হলো, যথেষ্ট বড় কম্পঙ্কের ক্ষেত্রে একটিমাত্র কোয়ান্টার শক্তিই বস্তুতে উপস্থিত মোট শক্তির চেয়ে বেশি। ফলে, বেশি কম্পাঙ্কের  (মানে বেশি শক্তির) বিকিরণ নির্গত হয় খুব কম। ফলে নির্গত বিকিরণে শক্তি অসীম আর হয় না। এভাবেই প্ল্যাঙ্ক বড় এক সমস্যার সহজ সমাধান করলেন। তবে প্ল্যাঙ্কের আগে বোলজম্যানও ১৮৮৭ সালে বিচ্ছিন্ন শক্তিস্তরের কথা বলেছিলেন।

যাই হোক, পরের দশকগুলোতে তত্ত্বটিকে সমৃদ্ধ করলেন বোর ও তাঁর শিষ্যরা। অবদান আছে আইনস্টাইনেরও। উল্লেখযোগ্য অবদান আছে ডি ব্রগলি, ম্যাক্স বর্ন, ডিরাক, হাইজেনবার্গ, পাউলি, ¯্রডিঙ্গহার ও ফাইনম্যানদেরও।  ততদিনে কোয়ান্টাম মেকানিক্সের আজব আজব কা-ে সবার চোখ ছানাবড়া। আইন্সটাইন তো কোয়ান্টাম তত্ত্বের বিরুদ্ধেই চলে গেলেন। সে নিয়ে বোরের সাথে রয়েছে কত মুখরোচক কাহিনি। 

## দ্বি-চির পরীক্ষা ও কণা-তরঙ্গের বহু রূপ {-}

একটি দেয়ালে দুটি ছিদ্র আছে। দেয়ালের অপর পাশে আছে একটি পর্দা। এখন দেয়ালে আলো ফেললে দুই ছিদ্র দিয়ে আসা আলো পর্দায় আলো-ছায়ার একটি নকশা তৈরি করবে। জানা কথা। কোথাও খুব অন্ধকার, কোথাও খুব উজ্জ্বল। কোথাও এর মাঝামাঝি অবস্থা। এখন কথা হলো, আলোর বদলে ইলেকট্রন নিক্ষেপ করলে কী হবে? পর্দার শুধু ছিদ্র বরাবর স্থানেই ইলেকট্রনের ধাক্কার রেশ থাকার কথা। কিন্তু না, এবারও নকশা পাওয়া গেল। আরও অদ্ভুত কথা হলো, এক ঝাঁক ইলেকট্রনের বদলে যদি একটিমাত্র ইলেকট্রনও নিক্ষেপ করা হয়, তবুও পাওয়া যায় নকশা। তার মানে ইলেকট্রনটি একই সাথে দুটো ছিদ্র দিয়েই যাচ্ছে! ঠিক তাই। সেটা সম্ভব হচ্ছে কণাটির তরঙ্গধর্মী আচরণের জন্যে। এই পরীক্ষার মাধ্যমেই জানা যায়, কণারাও তরঙ্গের মতো আচরণ করতে পারে। থমাস ইয়ং ১৮০১ সালে প্রথম পরীক্ষাটি পরিচালনা করেন। তবে সে সময় এর মূল গুরুত্ব বোঝা যায়নি। পরবর্তীতে ১৯২৪ সালে ডি ব্রগলি প্রমাণ করেন, সকল জড় পদার্থ তরঙ্গের মতো আচরণ করতে পারে। 

## অনিশ্চয়তা নীতি {-}

এ নীতি অনুসারে কোনো কণার অবস্থান ও গতিবেগ একই সাথে নিখুঁত করে মাপা যাবে না। এ দুটো বৈশিষ্ট্যের একটি যত ভালোভাবে পরমিাপ করার চেষ্টা করা হবে, অপরটি হয়ে পড়বে ততই অনিশ্চিত। সাধারণভাবে কণার অবস্থান ও বেগের কথা বলা হলেও আরও অনেকগুলো বিজড়িত রাশির জন্যে এ নীতিট প্রযোজ্য। যেমন কণার শক্তি ও স্থায়িত্ব, বিভিন্ন অক্ষের দিকে ঘূর্ণন, কোনো ক্ষেত্রের শক্তি ও তার পরিবর্তন ইত্যাদি। 
কোনো কণার অবস্থান বা বেগ জানার জন্যে কণাটিকে পর্যবেক্ষণ করতে হয়। আর সেটা করার জন্যে আলো ফেলতে হয় সেটির ওপরে। কিন্তু কণার আকার যেহেতু ছোট, তাই এর অবস্থান নিখুঁতভাবে জানতে ছোট তরঙ্গদৈর্ঘের আলো দরকার। কারণ, তরঙ্গদৈর্ঘ্যের পরিমাণের চেয়ে সূক্ষ্ম করে কণার অবস্থান জানা যায় না। একন ছোট তরঙ্গদৈর্ঘ্য মানে উচ্চ কম্পাঙ্ক। উচ্চ কম্পাপ্ক মানে উচ্চ শক্তি। তার মানে সূক্ষ অবস্থান জানতে হলে বেশি শক্তির আলো ফেলতে হবে। কিন্তু বেশি শক্তির এই আলো কণাটিকে অনেক বেশি উত্তেজিত করবে। ফলে এর অবস্থান জানা গেলেও বেগ হয়ে পড়বে অনিশ্চিত। আবার বেগের অনিশ্চয়তা কমিয়ে অর্ধেক করতে চাইলে অবস্থানের অনিশ্চয়তা হয়ে যাবে দ্বিগুণ। 

## কোয়ান্টাম এনটেঙ্গেলমেন্ট {-} 

আইনস্টাইন ব্যঙ্গ করে বলতেন ’স্পুকি অ্যাকশন অ্যাট অ্যা ডিসটেন্স’ বা ’দূর থেকে ভ’তুড়ে কা-’। কোয়ান্টাম এনটেঙ্গেলমেন্ট বা কোয়ান্টাম বিজড়ন প্রক্রিয়ার উদ্ভট ফলাফল নিয়েই তাঁর এই বক্তব্য। 

কথাটার মানে হলো, দুটি বিজড়িত কণা অনেক দূরে অবস্থান করেও পরস্পর নির্ভরশীল বৈশিষ্ট্যের অধিকারী হতে পারে। একে অপর থেকে যত দূরেই থাকুক, একের অবস্থান, ভরবেগ, ঘূর্ণন ইত্যাদি পুরোপুরি অন্যের ওপর নির্ভর করে। হোক তারা শত শত কোটি আলোকবর্ষ দূরে অবস্থিত। মনে করুন, কোনো স্ফটিক থেকে একটি লেজার রশ্মি নিক্ষিপ্ত হলো, যা একটিমাত্র ফোটন কণাকে ভেঙে দুটো বিজড়িত কণায় পরিণত করতে পারে। এখন দুটো ফোটন যদি দুদিকে রওয়ানা হয়ে যায়, পৌঁছে যায় লক্ষ কোটি আলোকবর্ষ দূরেও, তবু একটির যেকোনো বৈশিষ্ট্য পরিমাপ করা মাত্রই অপরটির বৈশিষ্ট্য জানা যাবে। যেমন একটি যদি স্পিন-আপ কণা হয়, তবে নিশ্চিত করে বলা যাবে, অপরটি হলো স্পিন-ডাউন কণা। যদি জানা যায়, একটি ঘুরছে ঘড়ির কাঁটার দিকে, তবে সাথে সাথে বলে দেওয়া যাবে, অপরটি ঘুরবে ঘড়ির কাঁটার উল্টো দিকে। তাদের দূরত্ব এক সেন্টিমিটার হোক কিংবা তারা মহাবিশে^র দুই আলাদা প্রান্তেই থাকুক সেটা বিবেচ্য নয়। এখানেই আইনস্টাইনের ঘোর আপত্তি। তাঁর মতে, একটি কণার কিছু ঘটলে তার প্রতিক্রিয়া তাৎক্ষণিকভাবে অন্যটির ওপর পড়তে পারে না। 
 
কারণ, (আপাত দৃষ্টিতে) লঙ্ঘিত হচ্ছে আপেক্ষিকতা তত্ত্বের অন্যতম একটি নীতি। কোনো তথ্যই আলোর চেয়ে বেশি বেগে যেতে পারে না। কিন্তু ১৯৬৪ সালে পদার্থবিদ জন বেল তাঁর ’বেল অসমতা’র মাধ্যমে প্রমাণ করেন, কণারা এমন পরস্পর-সম্পর্কযুক্ত আচরণ করতে পারে। যদিও তারা থাকে বহু বহু দূর। যে দূরত্বে আলোর চেয়ে দ্রুত কোনো তথ্য পৌঁছতে পারার কোনো কথা নয়। উপরন্ত প্রমাণ করেন, এমন ঘটনা ঘটতে কোনো সময়ই লাগে না। ফলে দূরত্ব কোনো প্রভাবই রাখতে পারে না এক্ষেত্রে। আসলে, কোয়ান্টাম বিজড়ন আপেক্ষিকতা নীতির বিরুদ্ধে যায় না। কারণ, আপেক্ষিকতার তত্ত্ব অনুসারে,  কোনো স্থান থেকে অন্য স্থানে আলোর চেয়ে দ্রুত তথ্য সরবরাহ করা সম্ভব নয়। আর কোয়ান্টাম বিজড়ন প্রক্রিয়ায় তথ্য প্রেরণ করা হয় না। এ কৌশল কাজে লাগিয়ে ঠিক আলোর চেয়ে দ্রুত তথ্য প্রেরণের কাজ সম্ভব নয়। 

পরবর্তীতে অসংখ্য পরীক্ষায় বেল অসমতার পক্ষে প্রমাণ পাওয়া গেছে। 

## কোয়ান্টাম ফ্লাকচুয়েশন {-}

এটি অনিশ্চয়তা নীতিরই একটি ফলাফল। আগেই বলেছি, নীতির একটি উদাহরণ হলো কোনো ক্ষেত্রের শক্তি ও তার পরিবর্তন। আমরা যাকে শূন্যস্থান বলি, অর্থাৎ, যেখানো কোনো পদার্থের অস্তিত্ব নেই, সেটাও আসলে ঠিক শূন্য নয়। অনিশ্চয়তা নীতি অনুসারে ক্ষেত্রের শক্তির মান ও তার পরিবর্তন একই সাথে সঠিক করে জানা যাবে না। তার মানে, শূন্যস্থানের কোনো ক্ষেত্রের মান ও পরিবর্তনের হার একই সাথে শূন্য হওয়া সম্ভব নয়। দুটোই শূন্য হওয়া মানে তো একই সাথে দুটোই নিখুঁতভাবে জানা হয়ে গেল। যা অসম্ভব। 
ফলে, আমরা যাকে শূন্যস্থান বলি সেখানেও অবিরত তৈরি হচ্ছে জোড়ায় কণা। এগুলোকে বলা হয় ভার্চুয়াল কণা।আর এ প্রক্রিয়ার নামই কোয়ান্টাম ফ্লাকচুয়েশন। এক সাথে তৈরি হয় এক জোড়া বিপরতি চার্জের কণা। সৃষ্টির পরমূহুর্তের আবার এরা একে অপরকে বিলীন করে দেয়। পল ডিরাকের আবিষ্কৃত কণা-প্রতিকণার ধর্ম অনুসারে। 

## সংরক্ষণশীলতা নীতির লঙ্ঘন {-} 
চিরায়ত পদার্থবিজ্ঞান অনুসারে শক্তির সৃষ্টি বা ধ্বংস সম্ভব নয়। সম্ভব শুধু রূপান্তর। কিন্তু অসম্ভবকে সম্ভব করাই কোয়ান্টাম মেকানিক্সের কাজ। ভার্চুয়াল কণা তৈরির সময়ই কণাগুলো তৈরির জন্যে শক্তি পায় কোথায়? এরা সমায়িক সময়ের সংরক্ষণশীলতা নীতি ভঙ্গ করে। ধার করে কিছু শক্তি। অল্প সময় পরে আবার বিলীন হওয়ার মাধ্যমে ফিরিয়ে দেয় সেই শক্তি। তবে বাইরে থেকে শক্তি সরবরাহ করা হলে ভার্চুয়াল কণা বাস্তব কণায় পরিণত হতে পারে। 

## কোয়ান্টাম টানেলিং {-} 
চলতে চলতে আপনার যদি একটি পুরু দেয়াল এসে যায়, তাহলে আপনার যাত্রা ওখানেই শেষ। কিন্তু অতিপারমাণবিক কণারা আপনার মতো হাল ছাড়ার পাত্র নয়। একটি প্রতিবন্ধকের পেছনে আটকা পড়া কোনো কণিকাকেও প্রতিবন্ধকের অপর পাশে দেখা যাবে তার একটি অশূন্য সম্ভাবনা রয়েছে। এটাও কণা-তরঙ্গের দ্বৈত আচরণের ফল। কণার জন্যে কাজটি যত কঠিন, তরঙ্গের জন্যে ততটা নয়। তেজস্ক্রিয় ক্ষয় প্রক্রিয়া সম্পন্ন হয় এই উপায়েই। নিউক্লিয়াস থেকে বেরিয়ে পড়ে আলফা কণা। 

## পরিমাপের আগে অস্তিত্বহীন? {-} 

আইনস্টাইন বলতেন, ‘তাহলে আমরা যখন তাকিয়ে থাকি না, তখন কি আকাশে চাঁদ থাকে না?’ কথাটা চাঁদের জন্যে সত্য না হলেও অতিপারমাণবিক জগতে কিন্তু সত্য। পর্যবেক্ষণের আগ পর্যন্ত কণার অস্তিত্বই থাকে না। ২০১৫ সালে নতুন আরেকটি পরীক্ষায় প্রমাণিত হয় এই কথা। অস্ট্রিয়ান পদার্থবিদ অ্যান্ড্রু ট্রাসকট নতুন করে এর প্রমাণ দেন। তিনি বলেন, ‘পরিমাপই সবকিছু। না তাকানো পর্যন্ত কোয়ান্টাম স্তরে বাস্তবতা বলতে কিছুই নেই।’ তাঁর দল পরীক্ষাটি চালান হিলিয়াম পরমাণু দিয়ে। 

**সূত্র:** অ্যা ব্রিফার হিস্ট্রি অব টাইম/স্টিফেন হকিং, এফন্যাল ডট জিওভি, ইউঅরিজন ডট এজু, ডিসকভার ম্যাগাজিন, নিউ অ্যাটলাস ডট কম, উইকিপিডিয়া।

- http://newton.ex.ac.uk/research/qsystems/people/jenkins/mbody/mbody2.html
- https://en.wikipedia.org/wiki/History_of_quantum_mechanics
- http://home.fnal.gov/~pompos/light/light_page28.html
- http://abyss.uoregon.edu/~js/21st_century_science/lectures/lec13.html
- http://discovermagazine.com/2005/jun/cover
- https://newatlas.com/quantum-theory-reality-anu/37866/

